# Our Website: www.dihoastore.net
# Email: dihoastore.mc@gmail.com
# Fanpage: www.facebook.com/dihoastore/

# Placeholder sử dụng cho Board: %ae-phoban_prefix% - Hiển thị tên của phó bản
#                                %ae-phoban_time% - Đếm ngược thời gian phòng chơi
#                                %ae-phoban_minplayers% - Người chơi tối thiểu
#                                %ae-phoban_maxplayers% - Người chơi tối đa của phòng
#                                %ae-phoban_<room name>_time% - Hiển thị thời gian của phòng
#                                %ae-phoban_<room name>_status% - Hiển thị trạng thái của phòng
#                                %ae-phoban_<room name>_minplayers% - Hiển thị số người tối thiểu của phòng
#                                %ae-phoban_<room name>_maxplayers% - Hiển thị số người tối đa của phòng
#                                %ae-phoban_point% - Điểm phó bản của tài khoản
#                                %ae-phoban_rank% - Vị trí xếp hạng của tài khoản trên bảng xếp hạng

#                                %ae-phoban_point_<player>% - Điểm phó bản của người chơi chỉ định
#                                %ae-phoban_rank_<player>% - Vị trí xếp hạng của người chơi chỉ định
#                                (Nếu đặt <player> = DiHoaStore thì sẽ hiện điểm của DiHoaStore)


Settings:
  # Lệnh được phép dùng khi trong phó bản
  CommandWhitelist:
    - "menu"
    - "tp(.*)"
    - "feed"
    - "heal"
    - "msg"
    - "shop"

  # Thời gian countdown khi bắt đầu phó bản (tính bằng giây)
  StartCountdown: 15

  # Thời gian countdown để qua đợt quái tiếp theo (tính bằng giây)
  StageCountdown: 15

  # Thời gian tự rời phó bản khi hoàn thành (tính bằng giây)
  QuitCountdown: 5

  # Sử dụng spawn mặc định sau khi hoàn thành phó bản
  # Nếu true: Người chơi sẽ được dịch chuyển về spawn đã đặt sẵn
  # Nếu false: Người chơi sẽ được dịch chuyển về vị trí trước khi vào phó bản
  UseDefaultSpawnAfterComplete: true
  
  # Khoảng cách quái sẽ xuất hiện theo từng đợt
  SpawnRadius: 2

  # Số lượt tham gia phó bản mặc định mỗi ngày của người chơi
  DefaultTurn: 1
  # Nếu để là day thì mỗi khi qua ngày mới sẽ cấp 1 lượt
  # Nếu để là hour thì mỗi giờ sẽ cấp 1 lượt
  # Số lượt cấp được tính theo DefaultTurn:
  AutoReset: day

  CommandAliases:
    - "pbp"
    - "pb"

  # Phần thưởng ở dạng Command cho toàn bộ người chơi khi hoàn tất phó bản
  RewardCommand:
    - eco give <player> 5000

  # Tự động dịch chuyển lại vị trí quái khi qua đợt quái mới
  TeleportNewStage: false

  # Khi chết sẽ cho người chơi ở trạng thái bảo vệ
  RespawnProtect: 3

  # Tự hồi sinh trong phó bản
  Respawn:
    # Bật/Tắt tính năng
    Enable: true

    # Số lượt tự hồi sinh trong phó bạn, khi hết lượt sẽ tự động thua phó bản
    # Ngoài ra có thể thêm perm cho người chơi phoban.respawn.<amount> thì lượt hồi sinh của người chơi sẽ tính theo perm
    Amount: 2

    # Countdown khi hồi sinh (tính bằng giây)
    Countdown: 3

  # Khi người chơi đang đi phó bản chết ở đâu thì sẽ hồi sinh lại ở chỗ đó
  Checkpoint: true

  # Khoảng thời gian giữa 2 mobs được spawn ra (tính bằng giây)
  MobSpawnDelay: 2

  # Tự bắt đầu phòng khi có 1 người vào (chỉnh thành true để bật)
  AutoStartSingle: false

  # Khi phòng chơi chưa full người mà đứa join đầu nó ko chịu start thì sau 600 giây (10 phút)
  # Thì sẽ kick hết ra khỏi room
  WaitingKick: 600

  # Con quái đầu tiên đc spawn ra của từng đợt thì sẽ phát sáng để người chơi dễ tìm đường tới
  MobStartGlow: true
  # Thời gian để mất hiệu ứng phát sáng (tính bằng giây)
  # Chỉnh 0 để hiện vĩnh viễn
  StartGlowFade: 15

  # Ngoài ra khi gần hết thời gian của đợt đó (15s)
  # Thì sẽ có 1 con quái đc phát sáng cho người chơi tìm tới
  MobEndingGlow: 15

Sound:
  # Tất cả tên Sound xem tại
  # https://helpch.at/docs/1.16.5/org/bukkit/Sound.html
  # Có thể thay 1.16.5 thành phiên bản hiện tại của Server

  # Sound khi bắt đầu từng đợt
  # Như mẫu bên dưới thì nếu sound ENTITY_ENDER_DRAGON_AMBIENT có tồn tại thì nó sẽ phát ra âm thanh đó
  # Nếu không tồn tại thì nó sẽ dùng sound ENTITY_ENDERDRAGON_AMBIENT và được ngăn cách với nhau bằng dấu | (có thể thêm nhiều tên)
  # Sound nào có tồn tại thì nó sẽ phát sound đó và dừng lại, những sound đằng sau nó sẽ không phát
  TurnStart: "ENTITY_ENDER_DRAGON_AMBIENT|ENTITY_ENDERDRAGON_AMBIENT"

Particle:
  # Tất cả tên Particle xem tại (hoặc có thể dùng lệnh)
  # https://helpch.at/docs/1.16.5/org/bukkit/Particle.html
  # https://helpch.at/docs/1.16.5/org/bukkit/Effect.html
  # Có thể thay 1.16.5 thành phiên bản hiện tại của Server

  # Particle khi đợt quái xuất hiện
  TurnStart: "cloud 0.3 1 0.3 0 8 normal"

  # Particle chỉ chỗ đợt quái xuất hiện tiếp theo
  NextTurn: "mobspawner_flames"

# Điểm phó bản mà người chơi sẽ mất hoặc nhận được khi tham gia phó bản
Point:
  # Cho phép điểm xuống số âm nếu để là true
  AllowNegative: false

  # Nhận từ 10 -> 30 điểm khi hoàn thành phó bản
  Win: "10:30"

  # Khi thua phó bản sẽ trừ từ 1 -> 30 điểm
  # Bao gồm cả việc chết hết lượt hồi sinh, out phó bản giữa chừng
  Lose: "1:30"

  # Khi chết sẽ trừ từ 1 -> 10 điểm
  Death: "1:10"
